"""
Handler for user-uploaded JavaScript templates.

User templates are JavaScript files that define 3D models parametrically.
They should define a generateSCAD() function that takes parameters and returns SCAD code.

The JavaScript execution happens in Next.js frontend, and the SCAD code is sent to backend.
"""

import uuid
import subprocess
from pathlib import Path
from typing import Dict, Any, Optional

from app.services.utils import JOBS_DIR as DEFAULT_JOBS_DIR, normalize_values

JOBS_DIR = DEFAULT_JOBS_DIR


def generate_stl_from_scad_code(
    scad_code: str,
    params: Dict[str, Any],
    template_id: Optional[str] = None,
) -> Optional[Path]:
    """
    Generate STL from pre-generated SCAD code.
    
    The SCAD code should have already been generated by the frontend
    (via executing the user's JavaScript template).
    
    Args:
        scad_code: Valid OpenSCAD code
        params: Parameters used during generation (for logging)
        template_id: Optional template ID for logging purposes
        
    Returns:
        Path to generated STL file, or None if generation failed
    """
    
    if not scad_code or not scad_code.strip():
        return None
    
    job_id = str(uuid.uuid4())
    
    try:
        # Write SCAD code to file
        scad_path = JOBS_DIR / f"{job_id}.scad"
        
        # Add comment header with metadata
        header_comment = "// Generated from user template"
        if template_id:
            header_comment += f": {template_id}"
        
        scad_path.write_text(f"{header_comment}\n\n{scad_code}")
        
        # Run OpenSCAD to generate STL
        stl_path = JOBS_DIR / f"{job_id}.stl"
        subprocess.run(
            ["openscad", "-o", str(stl_path), str(scad_path)],
            check=True,
            timeout=30,
        )
        
        return stl_path
    
    except subprocess.TimeoutExpired:
        print(f"Error: OpenSCAD generation timed out for template {template_id}")
        return None
    except Exception as e:
        print(f"Error generating STL from SCAD code: {e}")
        return None


def validate_scad_code(scad_code: str) -> tuple[bool, str]:
    """
    Validate SCAD code without running OpenSCAD.
    
    Basic validation to catch obvious issues before trying to render.
    """
    
    if not scad_code or not scad_code.strip():
        return False, "SCAD code is empty"
    
    # Check for basic SCAD syntax
    # Should contain at least one shape or transformation
    required_keywords = {
        'cube', 'sphere', 'cylinder', 'translate', 'rotate', 'scale',
        'union', 'difference', 'intersection', 'color', 'circle', 'square',
        'polygon', 'text', 'linear_extrude', 'rotate_extrude', 'hull',
        'minkowski'
    }
    
    code_lower = scad_code.lower()
    has_valid_keyword = any(f"{kw}(" in code_lower or f"{kw} (" in code_lower 
                            for kw in required_keywords)
    
    if not has_valid_keyword:
        return False, "SCAD code must contain at least one valid OpenSCAD function call"
    
    # Check for unmatched parentheses
    if code_lower.count('(') != code_lower.count(')'):
        return False, "Unmatched parentheses in SCAD code"
    
    # Check for unmatched brackets
    if code_lower.count('[') != code_lower.count(']'):
        return False, "Unmatched brackets in SCAD code"
    
    # Check for unmatched braces
    if code_lower.count('{') != code_lower.count('}'):
        return False, "Unmatched braces in SCAD code"
    
    return True, "Valid"
