/**
 * Utilities for working with user-uploaded templates
 */

export interface TemplateExecutionResult {
  success: boolean;
  scadCode?: string;
  error?: string;
}

/**
 * Execute a user template's JavaScript code with given parameters
 * 
 * @param jsCode - JavaScript template code (should define generateSCAD() function)
 * @param params - Parameters to inject into the template
 * @returns SCAD code generated by the template
 */
export async function executeTemplate(
  jsCode: string,
  params: Record<string, any>
): Promise<string> {
  const response = await fetch('/api/templates/execute', {
    method: 'POST',
    headers: {
      'Content-Type': 'application/json',
    },
    body: JSON.stringify({ jsCode, params }),
  });

  if (!response.ok) {
    const data = await response.json();
    throw new Error(data.error || 'Template execution failed');
  }

  const result = await response.json() as TemplateExecutionResult;
  if (!result.success || !result.scadCode) {
    throw new Error(result.error || 'Template produced no SCAD code');
  }

  return result.scadCode;
}

/**
 * Generate an example template for user reference
 */
export const TEMPLATE_EXAMPLE = `
// @param SIZE {number} Cube size in millimeters
var SIZE = 50;

// @param HOLLOW {boolean} Whether to make it hollow
var HOLLOW = false;

// @param THICKNESS {number} Wall thickness for hollow cubes
var THICKNESS = 2;

/**
 * This function will be called with the parameters above injected as globals
 * It should return valid OpenSCAD code as a string
 */
function generateSCAD() {
  let scad = '';
  
  if (HOLLOW) {
    // Create hollow cube by subtracting smaller cube
    scad = \`
difference() {
  cube([CODE{SIZE}, CODE{SIZE}, CODE{SIZE}], center=true);
  cube([CODE{SIZE - THICKNESS*2}, CODE{SIZE - THICKNESS*2}, CODE{SIZE - THICKNESS*2}], center=true);
}
    \`;
  } else {
    // Simple solid cube
    scad = \`cube([CODE{SIZE}, CODE{SIZE}, CODE{SIZE}], center=true);\`;
  }
  
  return scad;
}
`.replace(/CODE\{/g, '${');

/**
 * Validate that template code looks reasonable
 * (Basic client-side check before execution)
 */
export function validateTemplateCode(jsCode: string): { valid: boolean; message: string } {
  if (!jsCode || jsCode.trim().length === 0) {
    return { valid: false, message: 'Template code is empty' };
  }

  // Check for function definition
  if (!jsCode.includes('generateSCAD') && !jsCode.includes('generate')) {
    return {
      valid: false,
      message: 'Template must define a generateSCAD() or generate() function',
    };
  }

  // Check for obvious syntax errors
  const openParens = (jsCode.match(/\(/g) || []).length;
  const closeParens = (jsCode.match(/\)/g) || []).length;
  if (openParens !== closeParens) {
    return { valid: false, message: 'Unmatched parentheses' };
  }

  return { valid: true, message: 'OK' };
}

/**
 * Parse parameter definitions from template code
 */
export interface TemplateParameter {
  name: string;
  type: 'number' | 'string' | 'boolean';
  description: string;
  defaultValue: any;
}

export function extractParametersFromTemplate(jsCode: string): TemplateParameter[] {
  const parameters: TemplateParameter[] = [];
  const lines = jsCode.split('\n');

  for (let i = 0; i < lines.length; i++) {
    const line = lines[i].trim();

    // Look for @param style comments
    const paramMatch = line.match(/@param\s+(\w+)\s*(?:\{(\w+)\})?\s*(.*)/);
    if (paramMatch) {
      const [, name, type = 'number', description] = paramMatch;

      // Look for variable declaration
      for (let j = i + 1; j < Math.min(i + 5, lines.length); j++) {
        const varLine = lines[j].trim();
        const varMatch = varLine.match(
          new RegExp(`(?:var|const|let)\\s+${name}\\s*=\\s*([^;]+)`)
        );

        if (varMatch) {
          const defaultStr = varMatch[1].trim();
          let defaultValue: any = defaultStr;

          // Parse default value
          if (defaultStr === 'true') defaultValue = true;
          else if (defaultStr === 'false') defaultValue = false;
          else if (!isNaN(Number(defaultStr))) defaultValue = Number(defaultStr);
          else if (defaultStr.startsWith('"') || defaultStr.startsWith("'")) {
            defaultValue = defaultStr.slice(1, -1);
          }

          parameters.push({
            name,
            type: (type.toLowerCase() as any) || 'number',
            description: description.trim(),
            defaultValue,
          });
          break;
        }
      }
    }
  }

  return parameters;
}
